name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'

env:
  CHROME_BUILD_NUMBER: 117.0.5938.149

jobs:
  test:
    strategy:
      matrix:
        # https://github.com/federicocarboni/setup-ffmpeg/issues/21
#        os: [macos-13, ubuntu-latest, windows-latest]
        os: [macos-13]

    runs-on: ${{ matrix.os }}

    steps:
      # Windows fix. See https://github.com/actions/checkout/issues/226
      - run: git config --global core.autocrlf false

      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Cache browser
        id: cache-browser
        uses: actions/cache@v3
        with:
          path: browser
          key: ${{ runner.os }}-browser-${{ env.CHROME_BUILD_NUMBER }}

      - uses: FedericoCarboni/setup-ffmpeg@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'

      - run: yarn

      - if: runner.os == 'macOS'
        run: |
          cd ${{ github.workspace }}
          wget -O chrome-mac-x64.zip https://storage.googleapis.com/chrome-for-testing-public/${{ env.CHROME_BUILD_NUMBER }}/mac-x64/chrome-mac-x64.zip
          unzip chrome-mac-x64.zip
          export DEST=browser/chrome/mac-${{ env.CHROME_BUILD_NUMBER }}/chrome-mac-x64
          mkdir -p "$DEST"
          mv 'chrome-mac-x64/Google Chrome for Testing.app' "$DEST"/
      - if: runner.os != 'macOS'
        run: npx @puppeteer/browsers install chrome@${{ env.CHROME_BUILD_NUMBER }} --path ${{ github.workspace }}/browser

      - run: yarn tsc
      - run: yarn test
      - run: yarn lint

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: artifact
          path: |
            reactive-video-assets/test-output/
            reactive-video-assets/test-image-snapshots/__diff_output__/
